name: Changelog

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "🚀 Features",
                  "labels": ["feature"]
                },
                {
                  "title": "🐛 Fixes",
                  "labels": ["bug"]
                }
              ]
            }